"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-29 01:29:07.899328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Every ENUM type this migration creates (PostgreSQL only; see downgrade()).
ENUM_TYPES = (
    'assignmentstatus',
    'assignmenttargettype',
    'customertype',
    'devicestatus',
    'devicetype',
    'equipmentstatus',
    'equipmenttype',
    'kycstatus',
    'notificationtype',
    'outageseverity',
    'outagestatus',
    'outagetype',
    'plancategory',
    'planstatus',
    'plantype',
    'servicerequeststatus',
    'servicerequesttype',
    'simstatus',
    'simtype',
    'subscriptionstatus',
    'technicianavailability',
    'ticketcategory',
    'ticketpriority',
    'ticketstatus',
    'towerstatus',
    'towertype',
    'userrole',
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('customer_code', sa.String(length=32), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('customer_type', sa.Enum('PREPAID', 'POSTPAID', 'ENTERPRISE', name='customertype'), nullable=False),
    sa.Column('kyc_status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', name='kycstatus'), nullable=False),
    sa.Column('kyc_document_type', sa.String(length=64), nullable=True),
    sa.Column('kyc_document_number', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_customer_code'), 'customers', ['customer_code'], unique=True)
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=True)
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=True)
    op.create_table('outages',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('outage_type', sa.Enum('PLANNED', 'UNPLANNED', name='outagetype'), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='outageseverity'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', name='outagestatus'), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_resolution', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_resolution', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outages_severity'), 'outages', ['severity'], unique=False)
    op.create_index(op.f('ix_outages_status'), 'outages', ['status'], unique=False)
    op.create_table('service_plans',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('plan_type', sa.Enum('PREPAID', 'POSTPAID', name='plantype'), nullable=False),
    sa.Column('category', sa.Enum('DATA', 'VOICE', 'SMS', 'COMBO', name='plancategory'), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('validity_days', sa.Integer(), nullable=False),
    sa.Column('data_limit_mb', sa.Integer(), nullable=True),
    sa.Column('voice_limit_minutes', sa.Integer(), nullable=True),
    sa.Column('sms_limit_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='planstatus'), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_plans_code'), 'service_plans', ['code'], unique=True)
    op.create_table('sla_rules',
    sa.Column('ticket_category', sa.Enum('NETWORK_ISSUE', 'SIM_ISSUE', 'DATA_ISSUE', 'VOICE_ISSUE', 'DEVICE_ISSUE', 'ACCOUNT_ISSUE', 'SERVICE_REQUEST', name='ticketcategory'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='ticketpriority'), nullable=False),
    sa.Column('customer_type', sa.Enum('PREPAID', 'POSTPAID', 'ENTERPRISE', name='customertype'), nullable=False),
    sa.Column('response_time_minutes', sa.Integer(), nullable=False),
    sa.Column('resolution_time_minutes', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('towers',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('tower_type', sa.Enum('MACRO', 'MICRO', 'PICO', 'FEMTO', name='towertype'), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('coverage_radius_km', sa.Float(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'MAINTENANCE', 'OFFLINE', 'DECOMMISSIONED', name='towerstatus'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_towers_code'), 'towers', ['code'], unique=True)
    op.create_index(op.f('ix_towers_status'), 'towers', ['status'], unique=False)
    op.create_table('addresses',
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=32), nullable=False),
    sa.Column('line1', sa.String(length=255), nullable=False),
    sa.Column('line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=False),
    sa.Column('state', sa.String(length=128), nullable=False),
    sa.Column('postal_code', sa.String(length=32), nullable=False),
    sa.Column('country', sa.String(length=128), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_addresses_customer_id'), 'addresses', ['customer_id'], unique=False)
    op.create_table('network_equipment',
    sa.Column('tower_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('equipment_type', sa.Enum('ROUTER', 'SWITCH', 'BASE_STATION', 'OTHER', name='equipmenttype'), nullable=False),
    sa.Column('installation_date', sa.Date(), nullable=True),
    sa.Column('maintenance_schedule', sa.Date(), nullable=True),
    sa.Column('cpu_usage_percent', sa.Float(), nullable=False),
    sa.Column('memory_usage_percent', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('ONLINE', 'OFFLINE', 'DEGRADED', 'MAINTENANCE', name='equipmentstatus'), nullable=False),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tower_id'], ['towers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_network_equipment_status'), 'network_equipment', ['status'], unique=False)
    op.create_index(op.f('ix_network_equipment_tower_id'), 'network_equipment', ['tower_id'], unique=False)
    op.create_table('outage_affected_customers',
    sa.Column('outage_id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('notified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['outage_id'], ['outages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outage_affected_customers_customer_id'), 'outage_affected_customers', ['customer_id'], unique=False)
    op.create_index(op.f('ix_outage_affected_customers_outage_id'), 'outage_affected_customers', ['outage_id'], unique=False)
    op.create_table('outage_towers',
    sa.Column('outage_id', sa.String(length=36), nullable=False),
    sa.Column('tower_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['outage_id'], ['outages.id'], ),
    sa.ForeignKeyConstraint(['tower_id'], ['towers.id'], ),
    sa.PrimaryKeyConstraint('outage_id', 'tower_id')
    )
    op.create_table('service_requests',
    sa.Column('request_code', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('request_type', sa.Enum('SIM_REPLACEMENT', 'NUMBER_CHANGE', 'PLAN_CHANGE', 'DEVICE_REPLACEMENT', 'SERVICE_ACTIVATION', 'SERVICE_SUSPENSION', 'SERVICE_TERMINATION', name='servicerequesttype'), nullable=False),
    sa.Column('status', sa.Enum('SUBMITTED', 'IN_PROGRESS', 'APPROVED', 'REJECTED', 'COMPLETED', name='servicerequeststatus'), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_requests_customer_id'), 'service_requests', ['customer_id'], unique=False)
    op.create_index(op.f('ix_service_requests_request_code'), 'service_requests', ['request_code'], unique=True)
    op.create_index(op.f('ix_service_requests_status'), 'service_requests', ['status'], unique=False)
    op.create_table('sim_cards',
    sa.Column('sim_number', sa.String(length=32), nullable=False),
    sa.Column('sim_type', sa.Enum('PHYSICAL', 'ESIM', name='simtype'), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'ACTIVE', 'SUSPENDED', 'LOST', 'BLOCKED', 'DEACTIVATED', name='simstatus'), nullable=False),
    sa.Column('activation_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('customer_id', sa.String(length=36), nullable=True),
    sa.Column('current_plan_id', sa.String(length=36), nullable=True),
    sa.Column('serving_tower_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['current_plan_id'], ['service_plans.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['serving_tower_id'], ['towers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sim_cards_customer_id'), 'sim_cards', ['customer_id'], unique=False)
    op.create_index(op.f('ix_sim_cards_serving_tower_id'), 'sim_cards', ['serving_tower_id'], unique=False)
    op.create_index(op.f('ix_sim_cards_sim_number'), 'sim_cards', ['sim_number'], unique=True)
    op.create_index(op.f('ix_sim_cards_status'), 'sim_cards', ['status'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'OPS_MANAGER', 'SUPPORT_AGENT', 'NETWORK_ENGINEER', 'FIELD_TECHNICIAN', 'CUSTOMER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('previous_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity'), 'audit_logs', ['entity'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('devices',
    sa.Column('imei', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('manufacturer', sa.String(length=128), nullable=False),
    sa.Column('device_type', sa.Enum('SMARTPHONE', 'ROUTER', 'IOT', 'TABLET', 'OTHER', name='devicetype'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'BLOCKED', name='devicestatus'), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=True),
    sa.Column('sim_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['sim_id'], ['sim_cards.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sim_id')
    )
    op.create_index(op.f('ix_devices_customer_id'), 'devices', ['customer_id'], unique=False)
    op.create_index(op.f('ix_devices_imei'), 'devices', ['imei'], unique=True)
    op.create_table('notifications',
    sa.Column('recipient_user_id', sa.String(length=36), nullable=True),
    sa.Column('recipient_customer_id', sa.String(length=36), nullable=True),
    sa.Column('notification_type', sa.Enum('TICKET_ASSIGNMENT', 'SLA_BREACH', 'NETWORK_OUTAGE', 'SERVICE_RESTORATION', 'PLAN_EXPIRY', 'USAGE_THRESHOLD', 'SIM_SUSPENSION', 'MAINTENANCE_SCHEDULE', name='notificationtype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recipient_customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_notification_type'), 'notifications', ['notification_type'], unique=False)
    op.create_index(op.f('ix_notifications_recipient_customer_id'), 'notifications', ['recipient_customer_id'], unique=False)
    op.create_index(op.f('ix_notifications_recipient_user_id'), 'notifications', ['recipient_user_id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token', sa.String(length=512), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_jti'), 'refresh_tokens', ['jti'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('service_request_history',
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('from_status', sa.String(length=32), nullable=True),
    sa.Column('to_status', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['service_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_request_history_request_id'), 'service_request_history', ['request_id'], unique=False)
    op.create_table('sim_replacements',
    sa.Column('old_sim_id', sa.String(length=36), nullable=False),
    sa.Column('new_sim_id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['new_sim_id'], ['sim_cards.id'], ),
    sa.ForeignKeyConstraint(['old_sim_id'], ['sim_cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriptions',
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('sim_id', sa.String(length=36), nullable=False),
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'SUSPENDED', 'CANCELLED', 'EXPIRED', name='subscriptionstatus'), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auto_renew', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['service_plans.id'], ),
    sa.ForeignKeyConstraint(['sim_id'], ['sim_cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_customer_id'), 'subscriptions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_plan_id'), 'subscriptions', ['plan_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_sim_id'), 'subscriptions', ['sim_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_status'), 'subscriptions', ['status'], unique=False)
    op.create_table('technicians',
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('skills', sa.String(length=512), nullable=False),
    sa.Column('service_area', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('availability_status', sa.Enum('AVAILABLE', 'BUSY', 'OFF_DUTY', name='technicianavailability'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_technicians_availability_status'), 'technicians', ['availability_status'], unique=False)
    op.create_table('subscription_history',
    sa.Column('subscription_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('from_plan_id', sa.String(length=36), nullable=True),
    sa.Column('to_plan_id', sa.String(length=36), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['from_plan_id'], ['service_plans.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.ForeignKeyConstraint(['to_plan_id'], ['service_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_history_subscription_id'), 'subscription_history', ['subscription_id'], unique=False)
    op.create_table('technician_assignments',
    sa.Column('technician_id', sa.String(length=36), nullable=False),
    sa.Column('target_type', sa.Enum('TICKET', 'OUTAGE', name='assignmenttargettype'), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('ASSIGNED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='assignmentstatus'), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['technician_id'], ['technicians.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_technician_assignments_status'), 'technician_assignments', ['status'], unique=False)
    op.create_index(op.f('ix_technician_assignments_target_id'), 'technician_assignments', ['target_id'], unique=False)
    op.create_index(op.f('ix_technician_assignments_technician_id'), 'technician_assignments', ['technician_id'], unique=False)
    op.create_table('tickets',
    sa.Column('ticket_code', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.Enum('NETWORK_ISSUE', 'SIM_ISSUE', 'DATA_ISSUE', 'VOICE_ISSUE', 'DEVICE_ISSUE', 'ACCOUNT_ISSUE', 'SERVICE_REQUEST', name='ticketcategory'), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'ASSIGNED', 'IN_PROGRESS', 'WAITING_FOR_CUSTOMER', 'RESOLVED', 'CLOSED', name='ticketstatus'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='ticketpriority'), nullable=False),
    sa.Column('assigned_agent_id', sa.String(length=36), nullable=True),
    sa.Column('assigned_technician_id', sa.String(length=36), nullable=True),
    sa.Column('related_sim_id', sa.String(length=36), nullable=True),
    sa.Column('related_device_id', sa.String(length=36), nullable=True),
    sa.Column('escalated', sa.Boolean(), nullable=False),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_agent_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['assigned_technician_id'], ['technicians.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['related_device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['related_sim_id'], ['sim_cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_customer_id'), 'tickets', ['customer_id'], unique=False)
    op.create_index(op.f('ix_tickets_priority'), 'tickets', ['priority'], unique=False)
    op.create_index(op.f('ix_tickets_status'), 'tickets', ['status'], unique=False)
    op.create_index(op.f('ix_tickets_ticket_code'), 'tickets', ['ticket_code'], unique=True)
    op.create_table('usage_records',
    sa.Column('subscription_id', sa.String(length=36), nullable=False),
    sa.Column('sim_id', sa.String(length=36), nullable=False),
    sa.Column('usage_date', sa.Date(), nullable=False),
    sa.Column('data_used_mb', sa.Float(), nullable=False),
    sa.Column('voice_used_minutes', sa.Float(), nullable=False),
    sa.Column('sms_used_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sim_id'], ['sim_cards.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subscription_id', 'usage_date', name='uq_subscription_date')
    )
    op.create_index(op.f('ix_usage_records_sim_id'), 'usage_records', ['sim_id'], unique=False)
    op.create_index(op.f('ix_usage_records_subscription_id'), 'usage_records', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_usage_records_usage_date'), 'usage_records', ['usage_date'], unique=False)
    op.create_table('sla_tracking',
    sa.Column('ticket_id', sa.String(length=36), nullable=False),
    sa.Column('sla_rule_id', sa.String(length=36), nullable=False),
    sa.Column('sla_start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sla_deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('breached', sa.Boolean(), nullable=False),
    sa.Column('escalated', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sla_rule_id'], ['sla_rules.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sla_tracking_breached'), 'sla_tracking', ['breached'], unique=False)
    op.create_index(op.f('ix_sla_tracking_ticket_id'), 'sla_tracking', ['ticket_id'], unique=True)
    op.create_table('ticket_comments',
    sa.Column('ticket_id', sa.String(length=36), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_comments_ticket_id'), 'ticket_comments', ['ticket_id'], unique=False)
    op.create_table('ticket_history',
    sa.Column('ticket_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('from_value', sa.String(length=255), nullable=True),
    sa.Column('to_value', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_history_ticket_id'), 'ticket_history', ['ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_history_ticket_id'), table_name='ticket_history')
    op.drop_table('ticket_history')
    op.drop_index(op.f('ix_ticket_comments_ticket_id'), table_name='ticket_comments')
    op.drop_table('ticket_comments')
    op.drop_index(op.f('ix_sla_tracking_ticket_id'), table_name='sla_tracking')
    op.drop_index(op.f('ix_sla_tracking_breached'), table_name='sla_tracking')
    op.drop_table('sla_tracking')
    op.drop_index(op.f('ix_usage_records_usage_date'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_subscription_id'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_sim_id'), table_name='usage_records')
    op.drop_table('usage_records')
    op.drop_index(op.f('ix_tickets_ticket_code'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_status'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_priority'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_customer_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_technician_assignments_technician_id'), table_name='technician_assignments')
    op.drop_index(op.f('ix_technician_assignments_target_id'), table_name='technician_assignments')
    op.drop_index(op.f('ix_technician_assignments_status'), table_name='technician_assignments')
    op.drop_table('technician_assignments')
    op.drop_index(op.f('ix_subscription_history_subscription_id'), table_name='subscription_history')
    op.drop_table('subscription_history')
    op.drop_index(op.f('ix_technicians_availability_status'), table_name='technicians')
    op.drop_table('technicians')
    op.drop_index(op.f('ix_subscriptions_status'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_sim_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_plan_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_customer_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_table('sim_replacements')
    op.drop_index(op.f('ix_service_request_history_request_id'), table_name='service_request_history')
    op.drop_table('service_request_history')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_jti'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_notifications_recipient_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_recipient_customer_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_notification_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_devices_imei'), table_name='devices')
    op.drop_index(op.f('ix_devices_customer_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sim_cards_status'), table_name='sim_cards')
    op.drop_index(op.f('ix_sim_cards_sim_number'), table_name='sim_cards')
    op.drop_index(op.f('ix_sim_cards_serving_tower_id'), table_name='sim_cards')
    op.drop_index(op.f('ix_sim_cards_customer_id'), table_name='sim_cards')
    op.drop_table('sim_cards')
    op.drop_index(op.f('ix_service_requests_status'), table_name='service_requests')
    op.drop_index(op.f('ix_service_requests_request_code'), table_name='service_requests')
    op.drop_index(op.f('ix_service_requests_customer_id'), table_name='service_requests')
    op.drop_table('service_requests')
    op.drop_table('outage_towers')
    op.drop_index(op.f('ix_outage_affected_customers_outage_id'), table_name='outage_affected_customers')
    op.drop_index(op.f('ix_outage_affected_customers_customer_id'), table_name='outage_affected_customers')
    op.drop_table('outage_affected_customers')
    op.drop_index(op.f('ix_network_equipment_tower_id'), table_name='network_equipment')
    op.drop_index(op.f('ix_network_equipment_status'), table_name='network_equipment')
    op.drop_table('network_equipment')
    op.drop_index(op.f('ix_addresses_customer_id'), table_name='addresses')
    op.drop_table('addresses')
    op.drop_index(op.f('ix_towers_status'), table_name='towers')
    op.drop_index(op.f('ix_towers_code'), table_name='towers')
    op.drop_table('towers')
    op.drop_table('sla_rules')
    op.drop_index(op.f('ix_service_plans_code'), table_name='service_plans')
    op.drop_table('service_plans')
    op.drop_index(op.f('ix_outages_status'), table_name='outages')
    op.drop_index(op.f('ix_outages_severity'), table_name='outages')
    op.drop_table('outages')
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_index(op.f('ix_customers_customer_code'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###

    # PostgreSQL keeps ENUM types as separate objects: dropping the tables does not remove them,
    # and a later `upgrade` would then fail with "type already exists".
    if op.get_bind().dialect.name == "postgresql":
        for enum_name in ENUM_TYPES:
            op.execute(f"DROP TYPE IF EXISTS {enum_name}")
